name: grainy-dev
services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: grainy
      POSTGRES_PASSWORD: grainy
      POSTGRES_DB: grainy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grainy -d grainy"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - grainy-db:/var/lib/postgresql
  db-migrator:
    build:
      context: ..
      dockerfile: migrator.dockerfile
    environment:
      DATABASE_URL: postgres://grainy:grainy@db:5432/grainy
    depends_on:
      db:
        condition: service_healthy
  db-proxy:
    image: kvqn/db-proxy:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: grainy
      DATABASE_PASSWORD: grainy
      DATABASE_DB: grainy
      TOKEN: token
    depends_on:
      db:
        condition: service_healthy
      db-migrator:
        condition: service_completed_successfully
    ports:
      - "8080:80"
volumes:
  grainy-db:
